[default]
# CommonAPI-SomeIP runtime가 사용할 vsomeip 설정
vsomeip_config = vsomeip-client-sd.json
vsomeip_application_name = graphql

[proxy]
# "local:org.genivi.vehicle.playground.Playground:v1_0:1" 문자열은
# 네가 grep에서 이미 확인한 generated 코드에 박혀있는 값 그대로임.
local:org.genivi.vehicle.playground.Playground:v1_0:1 = 0xff40:0x0001
